version: '3'

services:
  api_autodromo:
    depends_on:
      - mongo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: DATABASE_URL
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db

volumes:
  mongodata:
