version: '3'

services:
#   api_autodromo:
#     depends_on:
#       - mongodb_autodromo
#     restart: always
#     build: .
#     env_file:
#       - .env
#     ports:
#       - '${PORT}:${PORT}'
#     environment:
#       DATABASE_URL: DATABASE_URL
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules

  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db

volumes:
  mongodata:
