version: '3.3'

services:
#   node-app:
#     build: .
#     image: node-app
#     environment:
#       - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
#     ports:
#       - '8085:8085'
#     depends_on:
#       - mongodb
#     volumes:
#       - .:/src
#     networks:
#       - node-network

  mongodb:
    image: mongo
    container_name: mongo_autodromo
    restart: always
    environment:
      MONGO_INITDB_ROOT_name: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
