services:
  mongodb:
    container_name: autodromo-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: autodromo-mongodb
    ports:
      - 27017:27017
    networks:
      - network

networks:
    network:
        driver: bridge
