POST http://localhost:4000/kart
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlX3Rva2VuIjoiZDRmM2YzZDktNTdmMS00NjcxLWE4ZDQtOTBhZjQ2NjIzYzRiIiwiaWF0IjoxNzE2OTIzNzgxfQ.s0LA6iL9ZC9k-hkJP0hkeqrEYVpN31O8cPNeE42KWfg

{
	"status": "AVAILABLE",
	"name": "Kart Five",
	"brand": "Ford",
	"model": "HB20",
	"power": 500,
	"tire_brand": "Sutran"
}
