GET http://localhost:4000/race/all
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlX3Rva2VuIjoiMjcwZDBiYzgtZjhmOS00YTNiLWI4YWItOTRmMzIzM2U3NTkyIiwiaWF0IjoxNzA2NjQwNzgxfQ.wU_GQPbAgiK38MBd_bfLOBD8QIeoqJqSv1jaWcfHAx8
