POST http://localhost:4000/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlX3Rva2VuIjoiNzQ1YmE5NGQtNDY5OS00NmM0LTllM2EtMDA2YjQ0MjM1ZDUwIiwiaWF0IjoxNzE2OTIwODY5fQ.N0GHQRlD4yNkQagSCzTUxo1wQiLVAFq1RO9_mdK73ds

{
	"name": "teste",
	"email": "user.test@gmail.com",
	"password": "testeBR@1234567",
	"role": "COMMON"
}
